/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goiUI;

import goiClass.Pho;
import goiClass.Monthem;
import goiClass.Monan;
import daocontroller.DAOthanhtoan;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Quang Truong
 */
public class banhang extends javax.swing.JFrame {

    private static String LoaitotmpString;
    private static String MonthemString;
    private static ArrayList<Monan> ListGioHang;
    
    private DefaultTableModel modelMonan;
    /**
     * Creates new form QuangTruong
     */
    public banhang() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelMonan = (DefaultTableModel) jTable1.getModel();
        ListGioHang = new ArrayList<>();
        modelMonan.setColumnIdentifiers(new Object[]{
            "STT", "Tên món ăn", "Loại", "Các loại thịt", "Số Lượng", "Giá"
        });
        showtablemonan();
    }

    void showtablemonan() {
        modelMonan.setRowCount(0);
        int i = 1;
        for (Monan monan : ListGioHang) {
            modelMonan.addRow(new Object[]{
                i++, monan.getTenmonString(), monan.getLoaitoString(), monan.getThitStrings(), monan.getSoluongint(), monan.getGiaFloat()
            });
        }

    }

    float tongtien() {
        float tongtientatca = 0;
        for (Monan monan : ListGioHang) {
            tongtientatca += monan.getGiaFloat();
        }
        return tongtientatca;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        loaito = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbGia1 = new javax.swing.JLabel();
        soluong = new javax.swing.JTextField();
        themmon = new javax.swing.JButton();
        lbGia2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        tfPay = new javax.swing.JButton();
        tfTienNhanCuaKach = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbTienthua = new javax.swing.JLabel();
        lbTongTien = new javax.swing.JLabel();
        lbTongTien1 = new javax.swing.JLabel();
        lbTongTien2 = new javax.swing.JLabel();
        lbTongTien3 = new javax.swing.JLabel();
        xoamonan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfSoban = new javax.swing.JTextField();
        xoamonan1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbGia = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        soluongmonthem = new javax.swing.JTextField();
        lbGia3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tenmonthem = new javax.swing.JComboBox<>();
        themmon1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Tên phở:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Loại tô:");

        loaito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loaito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Medium", "Special" }));
        loaito.setToolTipText("");
        loaito.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                loaitoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        loaito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loaitoActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Thịt:");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Tái");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Nạm");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Gân");

        jCheckBox4.setText("Gàu");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Số lượng:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Phở bò");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Giá:");

        lbGia1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbGia1.setText("0");

        soluong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        soluong.setText("1");
        soluong.setToolTipText("");
        soluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soluongActionPerformed(evt);
            }
        });
        soluong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                soluongKeyReleased(evt);
            }
        });

        themmon.setBackground(new java.awt.Color(255, 255, 204));
        themmon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        themmon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-goods.png"))); // NOI18N
        themmon.setText("Thêm món");
        themmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themmonActionPerformed(evt);
            }
        });

        lbGia2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbGia2.setText("VNĐ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(loaito, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(lbGia1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbGia2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(themmon, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(loaito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox1)
                        .addComponent(jCheckBox2)
                        .addComponent(jCheckBox3)
                        .addComponent(jCheckBox4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(lbGia1)
                            .addComponent(lbGia2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(themmon, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        tfPay.setBackground(new java.awt.Color(255, 255, 102));
        tfPay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pay (1).png"))); // NOI18N
        tfPay.setText("Pay");
        tfPay.setToolTipText("Thanh toán hóa đơn");
        tfPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPayActionPerformed(evt);
            }
        });

        tfTienNhanCuaKach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfTienNhanCuaKach.setText("0");
        tfTienNhanCuaKach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTienNhanCuaKachActionPerformed(evt);
            }
        });
        tfTienNhanCuaKach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTienNhanCuaKachKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tổng tiền:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tiền nhận của khách:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tiền thừa:");

        lbTienthua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTienthua.setText("0");

        lbTongTien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTongTien.setText("0");

        lbTongTien1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTongTien1.setText("VNĐ");

        lbTongTien2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTongTien2.setText("VNĐ");

        lbTongTien3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTongTien3.setText("VNĐ");

        xoamonan.setBackground(new java.awt.Color(255, 102, 102));
        xoamonan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        xoamonan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        xoamonan.setText("Xóa");
        xoamonan.setToolTipText("Xóa món ăn");
        xoamonan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoamonanActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Số bàn:");

        tfSoban.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfSoban.setText("1");
        tfSoban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSobanActionPerformed(evt);
            }
        });
        tfSoban.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSobanKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbTienthua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfTienNhanCuaKach, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(lbTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbTongTien1)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfSoban, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTongTien2)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lbTongTien3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(xoamonan)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPay)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(lbTongTien1)
                                .addComponent(jLabel7)
                                .addComponent(tfSoban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfTienNhanCuaKach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTongTien2))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbTienthua)
                            .addComponent(lbTongTien3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xoamonan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfPay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(245, 245, 245))
        );

        xoamonan1.setBackground(new java.awt.Color(255, 255, 255));
        xoamonan1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        xoamonan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        xoamonan1.setToolTipText("Quay về menu");
        xoamonan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoamonan1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐẶT MÓN");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jTable1.setSelectionBackground(new java.awt.Color(255, 204, 102));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Số lượng:");

        lbGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbGia.setText("0");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Giá:");

        soluongmonthem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        soluongmonthem.setText("1");
        soluongmonthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soluongmonthemActionPerformed(evt);
            }
        });
        soluongmonthem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                soluongmonthemKeyReleased(evt);
            }
        });

        lbGia3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbGia3.setText("VNĐ");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Các món thêm:");

        tenmonthem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tenmonthem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quẩy", "Hột gà", "Bánh phở", "Tiết hột gà", "Thịt thêm" }));
        tenmonthem.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                tenmonthemPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        tenmonthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenmonthemActionPerformed(evt);
            }
        });

        themmon1.setBackground(new java.awt.Color(255, 255, 204));
        themmon1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        themmon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-goods.png"))); // NOI18N
        themmon1.setText("Thêm món");
        themmon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themmon1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(201, 206, Short.MAX_VALUE)
                                .addComponent(jLabel11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(soluongmonthem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbGia, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbGia3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(themmon1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tenmonthem, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tenmonthem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(soluongmonthem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lbGia3)
                    .addComponent(lbGia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(themmon1)
                .addGap(45, 45, 45))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cafe.png"))); // NOI18N
        jLabel6.setText("Giỏ hàng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(641, 641, 641)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(xoamonan1)
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(xoamonan1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTienNhanCuaKachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTienNhanCuaKachKeyReleased

    }//GEN-LAST:event_tfTienNhanCuaKachKeyReleased

    private void loaitoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_loaitoPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_loaitoPopupMenuWillBecomeInvisible

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void soluongmonthemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soluongmonthemKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_soluongmonthemKeyReleased

    private void soluongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soluongKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_soluongKeyReleased

    private void loaitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loaitoActionPerformed
        // TODO add your handling code here: Combobox loai to
        try {
            int IndexSelect = loaito.getSelectedIndex();
            if (IndexSelect > 0) {
                LoaitotmpString = loaito.getItemAt(IndexSelect);
            } else {
                LoaitotmpString = loaito.getItemAt(0);
            }
            String giaString;
            switch (LoaitotmpString) {

                case "Small":
                    giaString = String.valueOf(45000 * Integer.parseInt(soluong.getText()));
                    lbGia1.setText(giaString);
                    break;
                case "Medium":
                    giaString = String.valueOf(60000 * Integer.parseInt(soluong.getText()));
                    lbGia1.setText(giaString);
                    break;
                case "Special":
                    giaString = String.valueOf(75000 * Integer.parseInt(soluong.getText()));
                    lbGia1.setText(giaString);
                    break;
                default:
                    lbGia1.setText("0");
                    break;
            }
        } catch (Exception e) {
            System.out.println("Loi phan chon to");
        }
    }//GEN-LAST:event_loaitoActionPerformed

    private void themmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themmonActionPerformed
        // TODO add your handling code here: them vao gio hang mon an
        if (!jCheckBox1.isSelected() && !jCheckBox2.isSelected() && !jCheckBox3.isSelected() && !jCheckBox4.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "Xin mời chọn loại thịt");
        } else {
            try {
                Monan pho = new Pho();
                pho.setTenmonString(jLabel17.getText());
                loaitoActionPerformed(evt);
                LoaitotmpString = (loaito.getSelectedIndex() == -1 ? loaito.getItemAt(0) : LoaitotmpString);
                pho.setLoaitoString(LoaitotmpString);
                pho.setSoluongint(Integer.parseInt(soluong.getText()));
                pho.setGiaFloat(Float.valueOf(lbGia1.getText()));
                String[] loaithit = new String[4];
                loaithit[0] = new String();
                loaithit[1] = new String();
                loaithit[2] = new String();
                loaithit[3] = new String();
                if (jCheckBox1.isSelected()) {
                    loaithit[0] = jCheckBox1.getText();
                }
                if (jCheckBox2.isSelected()) {
                    loaithit[1] = jCheckBox2.getText();
                }
                if (jCheckBox3.isSelected()) {
                    loaithit[2] = jCheckBox3.getText();
                }
                if (jCheckBox4.isSelected()) {
                    loaithit[3] = jCheckBox4.getText();
                }
                String thitdachonString = loaithit[0] + " " + loaithit[1] + " " + loaithit[2] + " " + loaithit[3];
                pho.setThitStrings(thitdachonString);
                ListGioHang.add(pho);
                lbTongTien.setText(String.valueOf(tongtien()));
                showtablemonan();
            } catch (NumberFormatException e) {
                System.out.println("Loi phan nhap");
            }
        }
    }//GEN-LAST:event_themmonActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void tenmonthemPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_tenmonthemPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_tenmonthemPopupMenuWillBecomeInvisible

    private void tenmonthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenmonthemActionPerformed
        // TODO add your handling code here: combobox mon an them
        int IndexSelect = tenmonthem.getSelectedIndex();
        if (IndexSelect > 0) {
            MonthemString = tenmonthem.getItemAt(IndexSelect);
        } else {
            MonthemString = tenmonthem.getItemAt(0);
        }
        String giamonString;
        switch (IndexSelect) {
            case 0:
                giamonString = (String.valueOf(5000 * Integer.parseInt(soluongmonthem.getText())));
                lbGia.setText(giamonString);
                break;
            case 1:
                giamonString = (String.valueOf(5000 * Integer.parseInt(soluongmonthem.getText())));
                lbGia.setText(giamonString);
                break;
            case 2:
                giamonString = (String.valueOf(10000 * Integer.parseInt(soluongmonthem.getText())));
                lbGia.setText(giamonString);
                break;
            case 3:
                giamonString = (String.valueOf(10000 * Integer.parseInt(soluongmonthem.getText())));
                lbGia.setText(giamonString);
                break;
            case 4:
                giamonString = (String.valueOf(15000 * Integer.parseInt(soluongmonthem.getText())));
                lbGia.setText(giamonString);
                break;
            case 5:
                giamonString = (String.valueOf(25000 * Integer.parseInt(soluongmonthem.getText())));
                lbGia.setText(giamonString);
                break;

            default:
                lbGia.setText("0");
                break;
        }
    }//GEN-LAST:event_tenmonthemActionPerformed

    private void soluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soluongActionPerformed
        // TODO add your handling code here:
        loaitoActionPerformed(evt);
    }//GEN-LAST:event_soluongActionPerformed

    private void soluongmonthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soluongmonthemActionPerformed
        // TODO add your handling code here:
        tenmonthemActionPerformed(evt);
    }//GEN-LAST:event_soluongmonthemActionPerformed

    private void themmon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themmon1ActionPerformed
        // TODO add your handling code here:
        try {
            Monan monthem = new Monthem();
            tenmonthemActionPerformed(evt);
            monthem.setTenmonString(MonthemString);
            monthem.setSoluongint(Integer.parseInt(soluongmonthem.getText()));
            monthem.setGiaFloat(Float.parseFloat(lbGia.getText()));
            monthem.setLoaitoString("Món thêm");
            ListGioHang.add(monthem);
            lbTongTien.setText(String.valueOf(tongtien()));
            showtablemonan();
        } catch (NumberFormatException e) {
            System.out.println("Loi phan them mon an them");
        }
    }//GEN-LAST:event_themmon1ActionPerformed

    private void tfPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPayActionPerformed
        // thanh toán
        tfTienNhanCuaKachActionPerformed(evt);
        if (ListGioHang.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Hãy thêm món ăn vào đơn hàng để thanh toán");
        } else if (Float.parseFloat(tfTienNhanCuaKach.getText()) < tongtien()) {
            JOptionPane.showMessageDialog(rootPane, "Số dư không đủ");
        } else {
            String tenhoadon = JOptionPane.showInputDialog(this, "Nhập tên hóa đơn đã thanh toán");
            if (tenhoadon.trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Xin mời nhập hóa đơn");
            } else {
                String tencacmonanString = "";
                int soluongcacmonan = 0;
                for (Monan monan : ListGioHang) {
                    tencacmonanString += monan.getTenmonString() + "(" + monan.getSoluongint() + ") ";
                    soluongcacmonan += monan.getSoluongint();
                }
                float giatong = tongtien();
                int ban = Integer.valueOf(tfSoban.getText());
                if (DAOthanhtoan.taohoadon(tenhoadon, tencacmonanString, soluongcacmonan, giatong, ban)) {
                    JOptionPane.showMessageDialog(rootPane, "Bạn đã thanh toán");
                    ListGioHang.clear();
                    showtablemonan();
                    // tra ve lai gia tri 0
                    lbTongTien.setText(String.valueOf(tongtien()));
                    tfTienNhanCuaKach.setText("0");
                    lbTienthua.setText("0");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Tên đơn hàng đã có");
                }
            }
        }
    }//GEN-LAST:event_tfPayActionPerformed

    private void xoamonanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoamonanActionPerformed
        // TODO add your handling code here:
        int selectIndex = jTable1.getSelectedRow();
        if (selectIndex == -1) {
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn 1 món ăn để xóa");
        } else if (ListGioHang.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Không có món ăn nào để xóa");
        } else {
            ListGioHang.remove(selectIndex);
            lbTongTien.setText(String.valueOf(tongtien()));
            showtablemonan();

        }

    }//GEN-LAST:event_xoamonanActionPerformed

    private void xoamonan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoamonan1ActionPerformed
        // TODO add your handling code here:// back home
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_xoamonan1ActionPerformed

    private void tfTienNhanCuaKachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTienNhanCuaKachActionPerformed
        // TODO add your handling code here:
        float tongtienhoadon = tongtien();
        float tiennhan = Float.parseFloat(tfTienNhanCuaKach.getText());
        if (tiennhan >= tongtienhoadon) {
            float tienthua = tiennhan - tongtienhoadon;
            lbTienthua.setText(String.valueOf(tienthua));
        } else {
            JOptionPane.showMessageDialog(rootPane, "Số dư không đủ để thanh toán");
        }
    }//GEN-LAST:event_tfTienNhanCuaKachActionPerformed

    private void tfSobanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSobanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSobanActionPerformed

    private void tfSobanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSobanKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSobanKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(banhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(banhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(banhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(banhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new banhang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbGia;
    private javax.swing.JLabel lbGia1;
    private javax.swing.JLabel lbGia2;
    private javax.swing.JLabel lbGia3;
    private javax.swing.JLabel lbTienthua;
    private javax.swing.JLabel lbTongTien;
    private javax.swing.JLabel lbTongTien1;
    private javax.swing.JLabel lbTongTien2;
    private javax.swing.JLabel lbTongTien3;
    private javax.swing.JComboBox<String> loaito;
    private javax.swing.JTextField soluong;
    private javax.swing.JTextField soluongmonthem;
    private javax.swing.JComboBox<String> tenmonthem;
    private javax.swing.JButton tfPay;
    private javax.swing.JTextField tfSoban;
    private javax.swing.JTextField tfTienNhanCuaKach;
    private javax.swing.JButton themmon;
    private javax.swing.JButton themmon1;
    private javax.swing.JButton xoamonan;
    private javax.swing.JButton xoamonan1;
    // End of variables declaration//GEN-END:variables
}
